# Generated by Django 2.2.7 on 2020-01-07 18:48

import LoginPortal.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='login_attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('ip', models.CharField(blank=True, default='UNKNOWN', max_length=50)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150)),
                ('mobile', models.IntegerField(blank=True)),
                ('city', models.CharField(default='Patna', max_length=15)),
                ('state', models.CharField(default='Bihar', max_length=15)),
                ('country', models.CharField(default='India', max_length=15)),
                ('branch', models.CharField(choices=[(1, 'IT'), (2, 'Comp'), (3, 'Chemical'), (4, 'Mechanical'), (5, 'Civil')], max_length=40)),
                ('profile_pic', models.ImageField(blank=True, default='profile_img/default.png', upload_to=LoginPortal.models.user_directory)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='file_handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.BooleanField(blank=True, default=False, null=True)),
                ('time', models.IntegerField(blank=True, default=0, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=150, null=True)),
                ('files', models.FileField(blank=True, default=None, null=True, upload_to=LoginPortal.models.user_directory_path)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(default=False, null=True)),
                ('friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoginPortal.info')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request', to='LoginPortal.info')),
            ],
            options={
                'unique_together': {('profile', 'friend')},
            },
        ),
    ]
