# Generated by Django 2.2.7 on 2019-12-27 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='login_attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('ip', models.CharField(blank=True, default='UNKNOWN', max_length=50)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150)),
                ('mobile', models.IntegerField(blank=True)),
                ('city', models.CharField(default='Patna', max_length=15)),
                ('state', models.CharField(default='Bihar', max_length=15)),
                ('country', models.CharField(default='India', max_length=15)),
                ('profile_pic', models.ImageField(blank=True, default='profile_img/default.png', upload_to='profile_img')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='file_handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, default=None, upload_to='received')),
                ('send_message', models.CharField(blank=True, max_length=1000)),
                ('receive_message', models.CharField(blank=True, max_length=1000)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
