# Generated by Django 2.2.7 on 2019-12-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_handler',
            name='receive_message',
        ),
        migrations.RemoveField(
            model_name='file_handler',
            name='send_message',
        ),
    ]
