# Generated by Django 2.2.7 on 2020-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='branch',
            field=models.CharField(choices=[(1, 'IT'), (2, 'Comp'), (3, 'Chemical'), (4, 'Mechanical'), (5, 'Civil')], default='1', max_length=20),
        ),
    ]
