# Generated by Django 2.2.7 on 2019-12-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPortal', '0002_auto_20191228_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_handler',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to='received'),
        ),
        migrations.AlterField(
            model_name='file_handler',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
