# Generated by Django 2.2.7 on 2020-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPortal', '0002_auto_20200108_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='branch',
            field=models.CharField(choices=[('1', 'IT'), ('2', 'Comp'), ('3', 'Chemical'), ('4', 'Mechanical'), ('5', 'Civil'), ('6', 'EnTc'), ('7', 'ETX')], max_length=20),
        ),
    ]
