# Generated by Django 2.2.7 on 2019-12-28 19:10

import LoginPortal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPortal', '0004_auto_20191228_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_handler',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to=LoginPortal.models.user_directory_path),
        ),
    ]
