# Generated by Django 2.2.7 on 2019-12-28 19:22

import LoginPortal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPortal', '0006_auto_20191228_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_img/default.png', upload_to=LoginPortal.models.user_directory),
        ),
    ]
