# Generated by Django 2.2.7 on 2019-12-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPortal', '0007_auto_20191228_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_handler',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='file_handler',
            name='downloaded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='file_handler',
            name='time',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
