# Generated by Django 2.2.7 on 2019-12-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPortal', '0008_auto_20191228_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_handler',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
